### ISSUE TITLE
Ubuntu 22.04: package requirement missmatch for AIDE

### ISSUE THREAD

**Issue by peedy2495** [ComplianceAsCode/content#10725]
#### Description of problem:

on remediaton or executing ansible fixes ansible will return an error on task "Ensure AIDE is installed": package crontabs not found

#### SCAP Security Guide Version:

0.1.67

#### Used setup:

policy: ssg-ubuntu2204-ds-1.2.xml
profile: cis_level2_workstation

#### Operating System Version:

Ubuntu 22.04.2

#### Additional Information/Debugging Steps:

crontabs has been merged into package cron

generated ansible fix section

```
- name: Ensure AIDE is installed
      package:
        name:
        - aide
        - crontabs
        state: present
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
      tags:
      - CJIS-5.10.1.3
      - NIST-800-53-CM-6(a)
      - NIST-800-53-SI-7
      - NIST-800-53-SI-7(1)
      - PCI-DSS-Req-11.5
      - PCI-DSSv4-11.5.2
      - aide_periodic_cron_checking
      - low_complexity
      - low_disruption
      - medium_severity
      - no_reboot_needed
      - restrict_strategy
```
