### ISSUE TITLE
content_rule_aide_build_database database DEPRECATED use 'database_in' instead

### ISSUE THREAD

**Issue by Commandcracker** [ComplianceAsCode/content#11425]
#### Description of problem:
content_rule_aide_build_database checks for `database` but not `database_in`
`WARNING: /etc/aide/aide.conf:10: Using 'database' is DEPRECATED and will be removed in the next release.. Update your config and use 'database_in' instead (line: 'database=file:/var/lib/aide/aide.db')`

#### SCAP Security Guide Version:
master
<details><summary>ssg-debian12-ds.xml (enhanced)</summary>
<p>

```
Document type: Source Data Stream
Imported: 2023-12-31T02:37:13

Stream: scap_org.open-scap_datastream_from_xccdf_ssg-debian12-xccdf.xml
Generated: (null)
Version: 1.3
Checklists:
        Ref-Id: scap_org.open-scap_cref_ssg-debian12-xccdf.xml
                Status: draft
                Generated: 2023-12-23
                Resolved: true
                Profiles:
                        Title: ANSSI-BP-028 (enhanced)
                                Id: xccdf_org.ssgproject.content_profile_anssi_bp28_enhanced
                        Title: ANSSI-BP-028 (high)
                                Id: xccdf_org.ssgproject.content_profile_anssi_bp28_high
                        Title: ANSSI-BP-028 (intermediary)
                                Id: xccdf_org.ssgproject.content_profile_anssi_bp28_intermediary
                        Title: ANSSI-BP-028 (minimal)
                                Id: xccdf_org.ssgproject.content_profile_anssi_bp28_minimal
                        Title: Profile for ANSSI DAT-NT28 Average (Intermediate) Level
                                Id: xccdf_org.ssgproject.content_profile_anssi_np_nt28_average
                        Title: Profile for ANSSI DAT-NT28 High (Enforced) Level
                                Id: xccdf_org.ssgproject.content_profile_anssi_np_nt28_high
                        Title: Profile for ANSSI DAT-NT28 Minimal Level
                                Id: xccdf_org.ssgproject.content_profile_anssi_np_nt28_minimal
                        Title: Profile for ANSSI DAT-NT28 Restrictive Level
                                Id: xccdf_org.ssgproject.content_profile_anssi_np_nt28_restrictive
                        Title: Standard System Security Profile for Debian 12
                                Id: xccdf_org.ssgproject.content_profile_standard
                Referenced check files:
                        ssg-debian12-oval.xml
                                system: http://oval.mitre.org/XMLSchema/oval-definitions-5
                        ssg-debian12-ocil.xml
                                system: http://scap.nist.gov/schema/ocil/2
Checks:
        Ref-Id: scap_org.open-scap_cref_ssg-debian12-oval.xml
        Ref-Id: scap_org.open-scap_cref_ssg-debian12-ocil.xml
        Ref-Id: scap_org.open-scap_cref_ssg-debian12-cpe-oval.xml
Dictionaries:
        Ref-Id: scap_org.open-scap_cref_ssg-debian12-cpe-dictionary.xml
```

</p>
</details>

#### Operating System Version:
Debain 12
`Linux *** 6.1.0-16-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.67-1 (2023-12-12) x86_64 GNU/Linux`
