### ISSUE TITLE
Rule ensure_redhat_gpgkey_installed is evaluated as notchecked on RHEL-10

### ISSUE THREAD

**Issue by matusmarhefka** [ComplianceAsCode/content#12407]
#### Description of problem:
The rule `ensure_redhat_gpgkey_installed` evaluates as notchecked (No candidate or applicable check found) on RHEL-10 which when combined with other gpgcheck rules in SCAP profiles (`gpgcheck_globally_activated`, `gpgcheck_never_disabled`, etc.) causes that it is not possible to install or update packages on hardened RHEL-10 system.

#### SCAP Security Guide Version:
db7b59bd68cbca5c6f536e2dd9ec8e3f8e0629cc

#### Operating System Version:
RHEL-10

**Comment by Mab879** [comment]
Once we fill the following in `products/rhel10/product.yml` that should resolve the issues.

```yaml
pkg_release: ""
pkg_version: ""
aux_pkg_release: ""
aux_pkg_version: ""

release_key_fingerprint: ""
auxiliary_key_fingerprint: ""
```
