### ISSUE TITLE
CIS benchmark for RHEL 8 wrong ID for a control

### ISSUE THREAD

**Issue by LivioZ** [ComplianceAsCode/content#12829]
#### Description of problem:
The ID of this control of CIS benchmark for RHEL 8 (v3.0.0) is actually 1.1.2.5.4 and not 1.1.3.5.4, it's probably a mistype.

I open an issue instead of a pull request because I don't know if changes are needed elsewhere.

```
- id: 1.1.3.5.4
    title: Ensure noexec option set on /var/tmp partition (Automated)
    levels:
      - l1_server
      - l1_workstation
    status: automated
    rules:
      - mount_option_var_tmp_noexec
```

#### SCAP Security Guide Version:
0.1.75
