### ISSUE TITLE
The `uefi` (and `non-uefi`) platform has incoherent conditionals

### ISSUE THREAD

**Issue by evgenyz** [ComplianceAsCode/content#13151]
#### Description of problem:

The `uefi` (and its counterpart `non-uefi`) platform has different conditionals across supported template types:

```yaml
name: cpe:/a:uefi
title: System boot mode is UEFI
# This OVAl check is based on presence of /sys/firmware/efi
check_id: system_boot_mode_is_uefi
bash_conditional: '[ -d /sys/firmware/efi ]'
ansible_conditional: '"/boot/efi" in ansible_mounts | map(attribute="mount") | list'
```
Conditionals must follow the same logic of applicability.

#### SCAP Security Guide Version:

0.1.76

Extract from #13006.
