### ISSUE TITLE
Clean 800-171 ansible remediation script has possible errors in regexp for auditd settings

### ISSUE THREAD

**Issue by justchris1** [ComplianceAsCode/content#2842]
#### Description of problem:
The following regexps will probably work, but I am unsure if the exact string was intended.  Take for example (Line 5394)
`^admin_space_left_action*`
It will match admin_space_left_actio (notice the lack of the n). 
Similar issue on Line 5440:
`^space_left_action*`

#### SCAP Security Guide Version:
Master v0.1.40

#### Operating System Version:
Centos 7.5

#### Steps to Reproduce:

1. Git Clone (git clone https://github.com/OpenSCAP/scap-security-guide.git)
2. cd scap-security-guide; cd build
3. cmake ../
4. make -j4
5. open scap-workbench and load locally built xml: usr/local/share/xml/scap/ssg/content/ssg-centos7-ds.xml
6. select profile 800-171
7. click - generate ansible remediation script (before running the scan)

#### Actual Results:
I think it will likely work, but probably isn't what is intended.

#### Expected Results:
At the least, I think this was probably intended:
`^admin_space_left_action.*`
although it may be advantageous to also check for a '=' to ensure it is matching an entire variable (with any amount of whitespace, including 0 until the '=' and from the start of the line):
`^\s*admin_space_left_action\s*=`
`^\s*space_left_action\s*=`

#### Addition Information/Debugging Steps:
It would also be great to include variable settings for 
```
var_auditd_space_left: 75
var_auditd_admin_space_left: 50
```
Perhaps, they were dropped because if they used regexp's that were based on the earlier ones (like ^space_left*) they would match the action commands.  However, they would not match the proposed improved regex's above.

The two stanza's to add could be:
```
    - name: Configure auditd admin_space_left for Low Disk Space
      lineinfile:
        dest: /etc/audit/auditd.conf
        line: "admin_space_left = {{ var_auditd_admin_space_left }}"
        regexp: "^\s*admin_space_left\s*="
      #notify: reload auditd
      tags:
        - auditd_data_retention_admin_space_left
        - medium_severity
        - restrict_strategy
        - low_complexity
        - low_disruption
        - CCE-27370-6
        - NIST-800-53-AU-1(b)
        - NIST-800-53-AU-4
        - NIST-800-53-AU-5(b)
        - NIST-800-53-IR-5
        - NIST-800-171-3.3.1
        - PCI-DSS-Req-10.7
        - CJIS-5.4.1.1
        - DISA-STIG-RHEL-07-030340   

    - name: Configure auditd admin_space_left Action on Low Disk Space
      lineinfile:
        dest: /etc/audit/auditd.conf
        line: "admin_space_left_action = {{ var_auditd_admin_space_left_action }}"
        regexp: "^\s*admin_space_left_action\s*="
      #notify: reload auditd
      tags:
        - auditd_data_retention_admin_space_left_action
        - medium_severity
        - restrict_strategy
        - low_complexity
        - low_disruption
        - CCE-27370-6
        - NIST-800-53-AU-1(b)
        - NIST-800-53-AU-4
        - NIST-800-53-AU-5(b)
        - NIST-800-53-IR-5
        - NIST-800-171-3.3.1
        - PCI-DSS-Req-10.7
        - CJIS-5.4.1.1
        - DISA-STIG-RHEL-07-030340
```
