### ISSUE TITLE
Rule ID used as task name in generated per-rule playbooks

### ISSUE THREAD

**Issue by matejak** [ComplianceAsCode/content#4195]
The playbook name uses rule ID, instead of more meaningful title. Consider the `sshd_disable_root_login` remediation:

```
- name: sshd_disable_root_login
  hosts: '@@HOSTS@@'
  become: true
  tags:
  - NIST-800-53-IA-2
  ...
  - low_complexity
  tasks:
  - name: Disable SSH Root Login
    lineinfile:
      create: true
      ...
```
