### ISSUE TITLE
new rule: enable rngd.service

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4472]
## Enable rngd
#sysctl enable rngd.service

**Comment by konstruktoid** [comment]
Example `ansible` task:

```
- name: rng-tools package installation
  become: 'yes'
  become_method: sudo
  package:
    name: rng-tools
    state: latest
  when: ansible_local.cpuinfo_rdrand
  tags:
    - rng-tools
    - packages
- security
```
`templates/etc/ansible/facts.d/cpuinfo_rdrand.fact`:
```
templates/etc/ansible/facts.d/cpuinfo_rdrand.fact
#!/bin/sh
if grep -sqo rdrand /proc/cpuinfo; then
  echo 'true'
else
  echo 'false'
fi
```

https://github.com/konstruktoid/ansible-role-hardening/blob/master/tasks/17_packages.yml
