### ISSUE TITLE
Fix rhel 8 task "Read files with incorrect hash" 

### ISSUE THREAD

**Issue by liveaverage** [ComplianceAsCode/content#4617]
#### Description of problem:

Current rhel8 task for "Read files with incorrect hash" introduces improper whitespace causing the task to fail every time (https://github.com/RedHatOfficial/ansible-role-rhel8-ospp/blob/master/tasks/main.yml#L612-L616). The same task calling the shell module for rhel7 (https://github.com/RedHatOfficial/ansible-role-rhel7-stig/blob/master/tasks/main.yml#L1334) works just fine, and updating the rhel8 role with the following works fine, too:

```
shell: 'set -o pipefail rpm -Va | grep -E ''^..5.* /(bin|sbin|lib|lib64|usr)/'' | awk ''{print $NF}'' '
```

Affected rule tests:
- https://static.open-scap.org/ssg-guides/ssg-sl8-guide-standard.html#xccdf_org.ssgproject.content_rule_rpm_verify_hashes

#### SCAP Security Guide Version:

Current version: 0.1.43

#### Operating System Version:

RHEL8 managed node:
- Red Hat Enterprise Linux release 8.0 (Ootpa) 4.18.0-80.4.2.el8_0.x86_64

Ansible control host:
- Red Hat Enterprise Linux Server release 7.5 (Maipo) 3.10.0-843.el7.x86_64
- ansible 2.8.1

#### Steps to Reproduce:

1. Install latest role via `ansible-galaxy install redhatofficial.rhel8_ospp`
2. Call from playbook:
  ```
- hosts: all
  tasks:
    - include_role:
        name: "RedHatOfficial.rhel7_stig"
      when: "ansible_facts['os_family'] == 'RedHat' and ansible_distribution_major_version == '7'"

    - include_role:
        name: "redhatofficial.rhel8_ospp"
      when: "ansible_facts['os_family'] == 'RedHat' and ansible_distribution_major_version == '8'"
  ```
3. Execute playbook: `ansible-playbook -i 'rh8.gxr.me,' prep_nist_stig.yml `

#### Actual Results:

 Repeated failure on task redhatofficial.rhel8.ospp: Read files with incorrect hash
  ```
TASK [redhatofficial.rhel8_ospp : Read files with incorrect hash] ****************************************
fatal: [rh8.gxr.me]: FAILED! => {"changed": false, "cmd": "set -o pipefail\nrpm -Va | grep -E '^..5.* /(bin|sbin|lib|lib64|usr)/' | awk '{print $NF}'\n", "delta": "0:00:07.288795", "end": "2019-07-13 13:03:28.493610", "msg": "non-zero return code", "rc": 1, "start": "2019-07-13 13:03:21.204815", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
  ```

#### Expected Results:

- RPMs with incorrect hashes should be enumerated, stored in var files_with_incorrect_hash, and remedied on the next task.
