### ISSUE TITLE
RedHatOfficial.rhel7_stig Ansible role fails on systems without NFS mounts

### ISSUE THREAD

**Issue by vhaispdeaded** [ComplianceAsCode/content#5006]
#### Description of problem:
The following tasks all use findmnt, which returns a non-zero status if no items are found:
* Get nfs and nfs4 mount points, that don't have noexec
* Get nfs and nfs4 mount points, that don't have nosuid
* Get nfs and nfs4 mount points, that don't have Kerberos security option

The following companion tasks are written to be skipped if the registered result is zero length, but this condition will never be met:
* Add noexec to nfs and nfs4 mount points
* Add nosuid to nfs and nfs4 mount points
* Add Kerberos security to nfs and nfs4 mount points

Need to add ignore_errors to findmnt tasks:
```YAML
  ignore_errors: yes
```
#### SCAP Security Guide Version:
Unsure of SCAP Security Guide Version used to generate this project.
[DISA STIG for Red Hat Enterprise Linux 7](https://github.com/RedHatOfficial/ansible-role-rhel7-stig) - release 0.1.47

#### Operating System Version:
Red Hat Enterprise Linux 7.7 built from Red Hat Satellite 6.6 and Ansible 2.8 (embedded in Satellite)

#### Steps to Reproduce:

1. Install RedHatOfficial.rhel7_stig using ansible-galaxy on system without NFS mounts
```Bash
ansible-galaxy install  RedHatOfficial.rhel7_stig
```
2. Test role using a simple Playbook
```YAML
  - name: Apply RedHatOfficial.rhel7_stig role
    include_role:
      name: RedHatOfficial.rhel7_stig
    when:
      - ansible_os_family == 'RedHat'
      - ansible_distribution_major_version is version_compare('7', '=')
```

#### Actual Results:
```
TASK [RedHatOfficial.rhel7_stig : Get nfs and nfs4 mount points, that don't have noexec] *******************************************************************************
fatal: [oitetnmulv107.vha.med.va.gov]: FAILED! => {"changed": false, "cmd": ["findmnt", "--fstab", "--types", "nfs,nfs4", "-O", "nonoexec", "-n"], "delta": "0:00:00.003898", "end": "2019-11-13 12:39:56.956918", "msg": "non-zero return code", "rc": 1, "start": "2019-11-13 12:39:56.953020", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

#### Expected Results:
```
TASK [RedHatOfficial.rhel7_stig : Get nfs and nfs4 mount points, that don't have noexec] *******************************************************************************
fatal: [oitetnmulv107.vha.med.va.gov]: FAILED! => {"changed": false, "cmd": ["findmnt", "--fstab", "--types", "nfs,nfs4", "-O", "nonoexec", "-n"], "delta": "0:00:00.003895", "end": "2019-11-13 14:27:42.367482", "msg": "non-zero return code", "rc": 1, "start": "2019-11-13 14:27:42.363587", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
...ignoring

TASK [RedHatOfficial.rhel7_stig : Add noexec to nfs and nfs4 mount points] *********************************************************************************************
skipping: [oitetnmulv107.vha.med.va.gov]

TASK [RedHatOfficial.rhel7_stig : Get nfs and nfs4 mount points, that don't have nosuid] *******************************************************************************
fatal: [oitetnmulv107.vha.med.va.gov]: FAILED! => {"changed": false, "cmd": ["findmnt", "--fstab", "--types", "nfs,nfs4", "-O", "nonosuid", "-n"], "delta": "0:00:00.004569", "end": "2019-11-13 14:27:43.543043", "msg": "non-zero return code", "rc": 1, "start": "2019-11-13 14:27:43.538474", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
...ignoring

TASK [RedHatOfficial.rhel7_stig : Add nosuid to nfs and nfs4 mount points] *********************************************************************************************
skipping: [oitetnmulv107.vha.med.va.gov]

TASK [RedHatOfficial.rhel7_stig : Get nfs and nfs4 mount points, that don't have Kerberos security option] *************************************************************
fatal: [oitetnmulv107.vha.med.va.gov]: FAILED! => {"changed": false, "cmd": ["findmnt", "--fstab", "--types", "nfs,nfs4", "-O", "nosec=krb5:krb5i:krb5p", "-n", "-o", "TARGET"], "delta": "0:00:00.003762", "end": "2019-11-13 14:27:44.707958", "msg": "non-zero return code", "rc": 1, "start": "2019-11-13 14:27:44.704196", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
...ignoring

TASK [RedHatOfficial.rhel7_stig : Add Kerberos security to nfs and nfs4 mount points] **********************************************************************************
skipping: [oitetnmulv107.vha.med.va.gov]
```

#### Addition Information/Debugging Steps:
Corrected tasks:
```YAML
- name: Get nfs and nfs4 mount points, that don't have noexec
  command: findmnt --fstab --types nfs,nfs4 -O nonoexec -n
  register: points_register
  check_mode: false
  changed_when: false
  ignore_errors: yes
  tags:
  - mount_option_noexec_remote_filesystems
  - medium_severity
  - configure_strategy
  - low_complexity
  - medium_disruption
  - no_reboot_needed
  - CCE-80436-9
  - NIST-800-53-AC-6
  - DISA-STIG-RHEL-07-021021
  when:
  - mount_option_noexec_remote_filesystems | bool
  - no_reboot_needed | bool
  - configure_strategy | bool
  - medium_severity | bool
  - medium_disruption | bool
  - low_complexity | bool

- name: Add noexec to nfs and nfs4 mount points
  mount:
    path: '{{ item.split()[0] }}'
    src: '{{ item.split()[1] }}'
    fstype: '{{ item.split()[2] }}'
    state: mounted
    opts: '{{ item.split()[3] }},noexec'
  when:
  - (points_register.stdout | length > 0)
  - mount_option_noexec_remote_filesystems | bool
  - no_reboot_needed | bool
  - configure_strategy | bool
  - medium_severity | bool
  - medium_disruption | bool
  - low_complexity | bool
  tags:
  - mount_option_noexec_remote_filesystems
  - medium_severity
  - configure_strategy
  - low_complexity
  - medium_disruption
  - no_reboot_needed
  - CCE-80436-9
  - NIST-800-53-AC-6
  - DISA-STIG-RHEL-07-021021

- name: Get nfs and nfs4 mount points, that don't have nosuid
  command: findmnt --fstab --types nfs,nfs4 -O nonosuid -n
  register: points_register
  check_mode: false
  changed_when: false
  ignore_errors: yes
  tags:
  - mount_option_nosuid_remote_filesystems
  - medium_severity
  - configure_strategy
  - low_complexity
  - medium_disruption
  - no_reboot_needed
  - CCE-80240-5
  - NIST-800-53-AC-6
  - DISA-STIG-RHEL-07-021020
  when:
  - mount_option_nosuid_remote_filesystems | bool
  - no_reboot_needed | bool
  - configure_strategy | bool
  - medium_severity | bool
  - medium_disruption | bool
  - low_complexity | bool

- name: Add nosuid to nfs and nfs4 mount points
  mount:
    path: '{{ item.split()[0] }}'
    src: '{{ item.split()[1] }}'
    fstype: '{{ item.split()[2] }}'
    state: mounted
    opts: '{{ item.split()[3] }},nosuid'
  when:
  - (points_register.stdout | length > 0)
  - mount_option_nosuid_remote_filesystems | bool
  - no_reboot_needed | bool
  - configure_strategy | bool
  - medium_severity | bool
  - medium_disruption | bool
  - low_complexity | bool
  tags:
  - mount_option_nosuid_remote_filesystems
  - medium_severity
  - configure_strategy
  - low_complexity
  - medium_disruption
  - no_reboot_needed
  - CCE-80240-5
  - NIST-800-53-AC-6
  - DISA-STIG-RHEL-07-021020

- name: Get nfs and nfs4 mount points, that don't have Kerberos security option
  command: findmnt --fstab --types nfs,nfs4 -O nosec=krb5:krb5i:krb5p -n -o TARGET
  register: points_register
  check_mode: false
  changed_when: false
  ignore_errors: yes
  tags:
  - mount_option_krb_sec_remote_filesystems
  - medium_severity
  - configure_strategy
  - low_complexity
  - medium_disruption
  - no_reboot_needed
  - CCE-27458-9
  - NIST-800-53-AC-14(1)
  - DISA-STIG-RHEL-07-040750
  when:
  - no_reboot_needed | bool
  - configure_strategy | bool
  - medium_severity | bool
  - mount_option_krb_sec_remote_filesystems | bool
  - medium_disruption | bool
  - low_complexity | bool

- name: Add Kerberos security to nfs and nfs4 mount points
  mount:
    path: '{{ item.split()[0] }}'
    src: '{{ item.split()[1] }}'
    fstype: '{{ item.split()[2] }}'
    state: mounted
    opts: '{{ item.split()[3] }},sec=krb5:krb5i:krb5p'
  when:
  - (points_register.stdout | length > 0)
  - no_reboot_needed | bool
  - configure_strategy | bool
  - medium_severity | bool
  - mount_option_krb_sec_remote_filesystems | bool
  - medium_disruption | bool
  - low_complexity | bool
  tags:
  - mount_option_krb_sec_remote_filesystems
  - medium_severity
  - configure_strategy
  - low_complexity
  - medium_disruption
  - no_reboot_needed
  - CCE-27458-9
  - NIST-800-53-AC-14(1)
  - DISA-STIG-RHEL-07-040750
```
