### ISSUE TITLE
DISA RHEL 7 STIG FIPS Rules incorrectly applied to virtual machines

### ISSUE THREAD

**Issue by Smithe2413** [ComplianceAsCode/content#5048]
#### Description of problem:
Virtual Machines (ec2 instances in this case) have the variable `ansible_virtualization_role` set to `guest` by default. This causes the Ansible Role to skip all of the FIPS enabling tasks. 

#### SCAP Security Guide Version:
Utilizing the RedHatOfficial role
https://github.com/RedHatOfficial/ansible-role-rhel7-stig

#### Operating System Version:
Red Hat Enterprise Linux Server release 7.7 (Maipo)
3.10.0-957.21.2.el7.x86_64

#### Steps to Reproduce:

1. Create VM or EC2 instance
2. Run the STIG Role
3. Observe the FIPS tasks are skipped. 
4.

#### Actual Results:
FIPS tasks are skipped and FIPS is not enabled

#### Expected Results:
FIPS tasks run and FIPS is correctly enabled for VMs.

**Comment by Smithe2413** [comment]
Also it is worth noting I removed the first "half" of the `when` statement for all the FIPS related tasks and re-ran the role. The FIPS controls were correctly applied. See below example. 

```
- name: install dracut-fips
  package:
    name: dracut-fips
    state: present
  when:
  - ansible_virtualization_role  != "docker"
  - high_complexity | bool
  - restrict_strategy | bool
  - reboot_required | bool
  - high_severity | bool
  - grub2_enable_fips_mode | bool
  - medium_disruption | bool
  tags:
  - grub2_enable_fips_mode
  - high_severity
  - restrict_strategy
  - high_complexity
  - medium_disruption
  - reboot_required
  - CCE-80359-3
  - NIST-800-53-IA-5
  - NIST-800-53-SC-13
  - NIST-800-53-AC-17(a)
  - NIST-800-53-AC-17(2)
  - NIST-800-53-IA-7
  - NIST-800-171-3.13.8
  - NIST-800-171-3.13.11
  - CJIS-5.10.1.2
  - DISA-STIG-RHEL-07-021350
```

**Comment by yuumasato** [comment]
@Smithe2413 Could also you tell us the value of `ansible_virtualization_type` in the VMs you are using?

**Comment by Smithe2413** [comment]
In my case, I was using AWS EC2 instances, Ansible facts set `ansible_virtualization_type` to `guest`

**Comment by yuumasato** [comment]
>  Ansible facts set `ansible_virtualization_type` to `guest`

I'm puzzled how `ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"` evaluates to false

**Comment by Smithe2413** [comment]
@yuumasato It's my understanding that
 ```
when: 
  - ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"` 
```
means that this task will only execute when `ansible_virtualization_role` **does not** equal `docker` or `guest`. Since VMs get the value `guest` assigned to them, the FIPS tasks do not run against those hosts.

**Comment by matejak** [comment]
> ... task will only execute when ansible_virtualization_role does not equal docker or guest.

The logical OR means that if any of those conditions is met, the task is supposed to be executed. So even if `ansible_virtualization_role` is `guest`, the task may still be executed - if `ansible_virtualization_type` is not `docker`.

In other words, removing a part of `or` makes the condition less likely to pass, so it doesn't make sense that it helped. It may either indicate a bug in Ansible, or the change was caused by something else.
The task has a lot of other conditions under `when`, and all individual sub-items are required to evaluate to true in order for the task to be executed. Could it be that it was in fact some other item that prevented the task execution?

**Comment by matejak** [comment]
I have managed to get hands on an Amazon instance, and I got these results:

When checking out the system facts, I have logged in and executed

```
ansible -m setup -c localhost localhost | grep virt
```

What I got on that particular Amazon instance was
```
...
"ansible_virtualization_role": "guest",
"ansible_virtualization_type": "xen",
```

which means that the condition

```
when:
 - ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"` 
```

would become

```
when:
 - False or True
```

which is True, i.e. the task execution is not blocked by particular condition.

I trust you that it was skipped, but that could have been caused by another conditions in the `when:` section. I don't know why do we have them there. My understanding is that if  we have `  - high_complexity | bool` in the `when` block, it will block the execution if `high_complexity` happens to be False. Tasks are tagged with those attribute (e.g. with the complexity, strategy, severity etc.), so having those under `when:` seems to be redundant.

**Comment by carlosmmatos** [comment]
Upon looking into this - there are a couple of things that need to be addressed:

- How should we best address checking for containers? 
    - I submitted an upstream [Ansible PR](https://github.com/ansible/ansible/pull/70697/files) to help address this issue, but the bottom line is that this logic won't be implemented until 2.11+, if it gets accepted.
    - We need to implement some logic now to help determine whether the target system is running in a container. Again, in RHEL we are stuck with an older version of Ansible that pretty much just tells you whether this is a docker container or not... it doesn't check for podman or others yet as it will down the pipeline of Ansible.

With that - here are some suggestions that I would like to open up for discussion:
> **NOTE:** Please notice that in my when clauses, I'm not checking for `ansible_virtualization_role != guest` as this seems self implied when explicitly declaring checks against `ansible_virtualization_type`. However please correct me if that assumption is incorrect.

- We can check for the different types of containers known to upstream [Ansible](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts/virtual/linux.py)
```yaml
when:
  - ansible_virtualization_type != "lxc"
  - ansible_virtualization_type != "docker"
  - ansible_virtualization_type != "podman"
  - ansible_virtualization_type != "container"
  - ansible_virtualization_type != "openvz"
```
Which is quite descriptive, but nasty to look at.

- Or we can set a variable (I'm not sure the best way to do this) somewhere with:
```yaml
container_list:
  - "lxc"
  - "docker"
  - "podman"
  - "container"
  - "openvz"

...
...

when: ansible_virtualization_type not in container_list
```
This is cleaner to look at it.

- Should we be trying to determine the type of container being used (as it's already implemented in future Ansible releases)?
