### ISSUE TITLE
Ignition snippets must use URL encoding for data

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#5586]
Some remediation functions like ``ansible_deregexify_banner_etc_issue`` also need to URL encode the payload during variable expansion.

For example

```yaml
# platform = multi_platform_rhel,multi_platform_fedora,multi_platform_ocp
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
spec:
  config:
    ignition:
      version: 2.2.0
    storage:
      files:
      - contents: data:,{{{ ansible_deregexify_banner_etc_issue("login_banner_text") }}}
        mode: 644
        path: /usr/lib/issue
        filesystem: root
```
