### ISSUE TITLE
Disable Ctrl-Alt-Del Burst Action, Redhat CoreOS

### ISSUE THREAD

**Issue by cynthia-rempel** [ComplianceAsCode/content#5886]
#### Description of problem:
The description tells the user to run a command locally instead of using machine config objects

#### SCAP Security Guide Version:
master branch

#### Operating System Version:
Redhat CoreOS 4.3

#### Steps to Reproduce:

1. Run compliance operator
2. Create a worker scan

#### Actual Results:
Description:

By default, SystemD will reboot the system if the Ctrl-Alt-Del key sequence is pressed Ctrl-Alt-Delete more than 7 times in 2 seconds.

To configure the system to ignore the CtrlAltDelBurstAction setting, add or modify the following to /etc/systemd/system.conf:

```
CtrlAltDelBurstAction=none
```

#### Expected Results:
Description

By default, SystemD will reboot the system if the Ctrl-Alt-Del key sequence is pressed Ctrl-Alt-Delete more than 7 times in 2 seconds.

To configure the system to ignore the CtrlAltDelBurstAction setting create a MachineConfig that sets /etc/systemd/system.conf in CtrlAltDelBurstAction=none

cp /etc/systemd/system.conf . 

Edit the copy to have:

CtrlAltDelBurstAction=none

Run
```
cat system.conf | base64 | tr -d '\n' > system.conf.base64
```
Put the string in

50-etc-systemd-system.yaml

```
# This example MachineConfig replaces /etc/systemd/system.conf with CtrlAltDelBurstAction=none
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 50-systemd-system-conf
spec:
  config:
    ignition:
      version: 2.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,W01hbmFnZXJdCkN0cmxBbHREZWxCdXJzdEFjdGlvbj1ub25lCgo=
        filesystem: root
        mode: 0644
        path: /etc/systemd/system.conf
```
Run

```
oc apply -f ./50-etc-systemd-system.yaml
```
