### ISSUE TITLE
'none_exist' check of template 'yamlfile_value' does not work as expected

### ISSUE THREAD

**Issue by tmishina** [ComplianceAsCode/content#6658]
(This issue was originally posted to https://github.com/openshift/compliance-operator/issues/585, and according to the comment given by @JAORMX in the issue I moved it to here)

#### Description of problem:
- 'none_exist' check of template 'yamlfile_value' does not work as expected

#### SCAP Security Guide Version:
- ContentImage: registry.redhat.io/openshift4/compliance-content-rhel8@sha256:0e7a2c857a368ad5c19f9cdf213e3f971ec6cfb86de19be60e34b369a97980e3
- Compliance Operator 0.1.26, installed from OperatorHub

#### Operating System Version:
- RHEL 8 (IBM Cloud Red Hat Kubernetes Service)

#### Steps to Reproduce:

1. create CRDs (scansetting, scansettingbinding, and tailoredprofile) - I will copy&paste their content if needed
2. apply the CRDs
3. `oc get compliancecheckresult | grep kubelet-authorization-mode` 

#### Actual Results:
```
roks-worker-master-kubelet-authorization-mode                                FAIL     medium
```

#### Expected Results:
```
roks-worker-master-kubelet-authorization-mode                                PASS     medium
```

#### Additional Information/Debugging Steps:
The target rule is [kubelet_authorization_mode](https://github.com/ComplianceAsCode/content/blob/master/applications/openshift/kubelet/kubelet_authorization_mode/rule.yml), and its contents is as follows.

```yaml
template:
    name: yamlfile_value
    vars:
        filepath: /etc/kubernetes/kubelet.conf
        yamlpath: ".authorization.mode"
        check_existence: "none_exist"
        values:
         - value: "AlwaysAllow"
           operation: "equals"
```

Check target is `kubelet.conf`, and its contents is as follows.

```
# cat /etc/kubernetes/kubelet.conf | grep 'authorization' -A 2
authorization:
  mode: "Webhook"
```

The log the scanner Pod says 'exist on the system', but the content (`mode: "Webhook"`) does not match the value in the rule (`value: "AlwaysAllow"`).

```
Title  Ensure authorization is set to Webhook
Rule   xccdf_org.ssgproject.content_rule_kubelet_authorization_mode
Ident  CCE-83593-4
I: oscap: Evaluating XCCDF rule 'xccdf_org.ssgproject.content_rule_kubelet_authorization_mode'.
I: oscap: Evaluating definition 'oval:ssg-installed_app_is_ocp4:def:1': Red Hat OpenShift Container Platform.
I: oscap: Definition 'oval:ssg-installed_app_is_ocp4:def:1' evaluated as false.
I: oscap: Evaluating definition 'oval:ssg-installed_app_is_ocp4_node:def:1': Red Hat OpenShift Container Platform Node.
I: oscap: Definition 'oval:ssg-installed_app_is_ocp4_node:def:1' evaluated as true.
I: oscap: This rule requires an OCIL check. OCIL checks are not supported by OpenSCAP.
I: oscap: Evaluating definition 'oval:ssg-kubelet_authorization_mode:def:1': Ensure authorization is set to Webhook.
I: oscap:   Evaluating yamlfilecontent test 'oval:ssg-test_kubelet_authorization_mode:tst:1': In the file '/etc/kubernetes/kubelet.conf' find only one object at path '.authorization.mode'..
I: oscap:     Querying yamlfilecontent object 'oval:ssg-object_kubelet_authorization_mode:obj:1', flags: 0.
I: oscap:     Creating new syschar for yamlfilecontent_object 'oval:ssg-object_kubelet_authorization_mode:obj:1'.
I: oscap:     Object 'oval:ssg-object_kubelet_authorization_mode:obj:1' references variable 'oval:ssg-kubelet_authorization_mode_file_location:var:1' in 'filepath' field.
I: oscap:     Querying variable 'oval:ssg-kubelet_authorization_mode_file_location:var:1'.
I: oscap:     Variable 'oval:ssg-kubelet_authorization_mode_file_location:var:1' has values "/etc/kubernetes/kubelet.conf".
I: oscap:     Switching probe to PROBE_OFFLINE_OWN mode.
I: oscap:     I will run yamlfilecontent_probe_main:
I: oscap:     Opening file '/host/etc/kubernetes/kubelet.conf'.
I: oscap:     Test 'oval:ssg-test_kubelet_authorization_mode:tst:1' requires that none of the objects defined by 'oval:ssg-object_kubelet_authorization_mode:obj:1' exist on the system.
I: oscap:     1 objects defined by 'oval:ssg-object_kubelet_authorization_mode:obj:1' exist on the system.
I: oscap:     All items matching object 'oval:ssg-object_kubelet_authorization_mode:obj:1' were collected. (flag=complete)
I: oscap:   Test 'oval:ssg-test_kubelet_authorization_mode:tst:1' evaluated as false.
I: oscap: Definition 'oval:ssg-kubelet_authorization_mode:def:1' evaluated as false.
Result fail
```

**Comment by JAORMX** [comment]
@yuumasato @evgenyz could you take a look at this?

**Comment by JAORMX** [comment]
@tmishina can you try:

```
template:
    name: yamlfile_value
    vars:
        filepath: /etc/kubernetes/kubelet.conf
        yamlpath: ".authorization.mode"
        values:
         - value: "AlwaysAllow"
           operation: "equals"
           entity_check: "none satisfy"
```

**Comment by tmishina** [comment]
@JAORMX Thank you for suggestion, I've tried this rule but the result is `FAIL`.

```
% oc get compliancecheckresult| grep mode
workers-scan-kubelet-authorization-mode                                FAIL     medium
```

`kubelet.conf` of test target (CRC host) is as follows. It does not contain `.authorization.mode` and thus result should be `PASS`.

```yaml
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  x509:
    clientCAFile: /etc/kubernetes/kubelet-ca.crt
  anonymous:
    enabled: false
cgroupDriver: systemd
cgroupRoot: /
clusterDNS:
  - 172.25.0.10
clusterDomain: cluster.local
containerLogMaxSize: 50Mi
maxPods: 250
kubeAPIQPS: 50
kubeAPIBurst: 100
rotateCertificates: true
serializeImagePulls: false
staticPodPath: /etc/kubernetes/manifests
systemCgroups: /system.slice
systemReserved:
  cpu: 500m
  memory: 1Gi
  ephemeral-storage: 1Gi
featureGates:
  APIPriorityAndFairness: true
  LegacyNodeRoleBehavior: false
  NodeDisruptionExclusion: true
  RotateKubeletServerCertificate: true
  SCTPSupport: true
  ServiceNodeExclusion: true
  SupportPodPidsLimit: true
serverTLSBootstrap: true
```
