### ISSUE TITLE
Processing of extra_ovals.py does not support product qualifiers

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#6659]
Our [extra_ovals.yml](https://github.com/ComplianceAsCode/content/blob/master/shared/templates/extra_ovals.yml) processing doesn't seem to support product qualifiers (i.e. `servicename@rhel7` `packagename@sle12`, etc)
The following code in extra_ovals.py does not process the `sle12` product as expected.
```
service_sssd_disabled:
  name: service_disabled
  vars:
    servicename: sssd
    packagename: sssd-common
    packagename@sle12: sssd
```

_Originally posted by @ggbecker in https://github.com/ComplianceAsCode/content/issues/6632#issuecomment-790681210_
