### ISSUE TITLE
Duplicate STIGID for RHEL 8 / require_emergency_target_auth

### ISSUE THREAD

**Issue by cipherboy** [ComplianceAsCode/content#6925]
#### Description of problem:

In `require_emergency_target_auth`:

```yaml
references:
    stigid@rhel7: RHEL-07-010481
    stigid@rhel8: RHEL-08-010151   # <-- Here?
    stigid@ol7: OL07-00-010481
    stigid@rhel8: RHEL-08-010152   # <-- Or here?
```

I'm not sure how to resolve, but it'll be a blocker for #6882. @carlosmmatos -- mind taking a look? I've got no idea which to choose... :) Thanks!

If I merge them together on one key I get:

```
RuntimeError: Error normalizing 'require_emergency_target_auth': Rules can not have multiple STIG IDs.
```

#### SCAP Security Guide Version:

`master` as of https://github.com/ComplianceAsCode/content/commit/6b8a62c644fbc4da1e08fa0cb7a8098057398e01.
