### ISSUE TITLE
Multiple issues with rhel7-playbook-stig.yml in scap-security-guide RPM

### ISSUE THREAD

**Issue by salanisor** [ComplianceAsCode/content#7078]
#### Description of problem:
Currently working through applying the RHEL 7 stig playbook provided in the scap-security-guide to RHEL 7.9 AWS AMI.

Running into a couple of issues.

1. In the current version there's double entries for `login_banner_text:`
2. No idempotent configuration not to add a boot=uuid=xxxx entry in grub when /boot and / partitions equal the same as it is the case when deploying a RHEL AMI on AWS.
3. No idempotent configuration check when `firewall-cmd` is executed when the `firewalld` package is not installed.
4. No boolean option out of the box to disable task:  `Remove lines containing NOPASSWD from sudoers files` breaking the only user `ec2-user` with privileged access on a RHEL 7 base AMI.

#### SCAP Security Guide Version:
```
# Benchmark ID:  RHEL-7
# Benchmark Version:  0.1.54
# XCCDF Version:  1.1
```

#### Operating System Version:
RHEL 7.9

#### Steps to Reproduce:

1. Apply the playbook on a RHEL 7 base AMI.
```
ansible-playbook -i inventory.ini playbook.yml
```

#### Actual Results:

- RHEL 7 AMI is unable to boot (bricked) giving the following errors in the console:
```
513 [    5.441969] dracut: FATAL: FIPS integrity test failed
514 [    5.448020] dracut: Refusing to continue
```

Looks like there's a [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1672737) filed for this already but no fix for it implemented in the current playbook.

Also, the following task `Remove lines containing NOPASSWD from sudoers files` that breaks the playbook itself because of the manner in which the ec2-user is configured with the `NOPASSWD` for the `%wheel` group in the RHEL 7 base AMI.

Lastly, the following tasks regarding `firewalld` is not completely idempotent causing the playbook to fail because as can be seen below, the `Enable service firewalld` is executed when `'"firewalld" in ansible_facts.packages'`, but the immediate task that follows doesn't have this `when` check and executes `firewall-cmd` when the package is not installed causing it to fail.

```
    - name: Enable service firewalld
      block:

        - name: Gather the package facts
          package_facts:
            manager: auto

        - name: Enable service firewalld
          service:
            name: firewalld
            enabled: 'yes'
            state: started
          when:
            - '"firewalld" in ansible_facts.packages'
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
      tags:
        - CCE-80998-8
        - DISA-STIG-RHEL-07-040520
        - NIST-800-171-3.1.3
        - NIST-800-171-3.4.7
        - NIST-800-53-AC-4
        - NIST-800-53-CA-3(5)
        - NIST-800-53-CM-6(a)
        - NIST-800-53-CM-7(b)
        - NIST-800-53-SC-7(21)
        - enable_strategy
        - low_complexity
        - low_disruption
        - medium_severity
        - no_reboot_needed
        - service_firewalld_enabled

    - name: Configure rate limiting direct rule for firewalld
      command: firewall-cmd --permanent --direct --add-rule ipv4 filter INPUT_direct 0
        -p tcp -m limit --limit 25/minute --limit-burst 100  -j INPUT_ZONES
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
      tags:
        - CCE-80542-4
        - DISA-STIG-RHEL-07-040510
        - NIST-800-53-CM-6(a)
        - NIST-800-53-SC-5
        - NIST-800-53-SC-5(1)
        - NIST-800-53-SC-5(2)
        - NIST-800-53-SC-5(3)(a)
        - configure_firewalld_rate_limiting
        - configure_strategy
        - low_complexity
        - low_disruption
        - medium_severity
        - no_reboot_needed
```

#### Expected Results:
Playbook to allow boolean option to disable the removal of `NOPASSWD` in sudoers (optional) but be able to complete the application of the stig playbook without the issues mentioned above.
