### ISSUE TITLE
Missing variable for package_tftp-server_removed

### ISSUE THREAD

**Issue by Prodian0013** [ComplianceAsCode/content#7092]
#### Description of problem:
Missing variable conditional for package_tftp-server_removed

#### SCAP Security Guide Version:
ansible-role-rhel8-stig 0.1.52

#### Operating System Version:
RHEL 8.2

#### Steps to Reproduce:

1. set variable to package_tftp-server_removed: false
2. 
3.
4.

#### Actual Results:
Removes still removes tftp-server package

#### Expected Results:
Doesnt remove tftp-server package.

**Comment by cipherboy** [comment]
@Prodian0013 Could you accomplish this by tailoring the profile and simply removing this rule? A variable shouldn't be needed for this -- you'd have to tailor the profile either to modify the value or to remove the rule, so removing the rule is simpler IMO. Is there a reason that wouldn't work for your use case?

**Comment by Prodian0013** [comment]
Yeah Im not generating profiles Im simply using the released ansible role from redhat https://galaxy.ansible.com/RedHatOfficial/rhel8_stig

**Comment by marcusburghardt** [comment]
@Prodian0013 , I assume the involved rule is `package_tftp-server_removed`:
https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/services/obsolete/tftp/package_tftp-server_removed/rule.yml

If so, this rule expects the removal of `tftp-server` package. However, there is not remediation for this specific rule to ensure that.
So, the `Expected Result` of not removing tftp-server package should already be true.
Could you give more details to reproduce this, please?

Anyways, supposing this rule has a remediation in place, creating a conditional there where the remediation would not actually remove the package would create inconsistency with the rule objective. In other words it would be an unnecessary remediation which actually does not remediate.

As described in the rule:
```
If TFTP is required for operational support (such as transmission of router
    configurations), its use must be documented with the Information Systems
    Securty Manager (ISSM), restricted to only authorized personnel, and have
    access control rules established.
``` 
So, if you don't want a fail state for this rule, I would suggest to tailoring the profile to not consider this rule, as mentioned by @cipherboy and documenting it, as described in the rule description.

**Comment by marcusburghardt** [comment]
Leaving this issue open as good-first-issue. It would be nice to have a remediation for this rule.

**Comment by ggbecker** [comment]
One alternative method of skipping the tasks that remove the package is simply running the ansible command with the option:

`--skip-tags package_tftp-server_removed`

This should skip all the tasks that perform the package removal.

**Comment by ggbecker** [comment]
> If so, this rule expects the removal of `tftp-server` package. However, there is not remediation for this specific rule to ensure that.
> So, the `Expected Result` of not removing tftp-server package should already be true.
> Could you give more details to reproduce this, please?

This is actually a templated rule and the remediation is automatically generated by the build system. https://github.com/ComplianceAsCode/content/blob/master/shared/templates/package_removed/bash.template

**Comment by Prodian0013** [comment]
Its just seems a little inconsistent to have the ability remove/install these packages but not the tftp-server package.

```
package_abrt_removed: true
package_aide_installed: true
package_audit_installed: true
package_fapolicyd_installed: true
package_firewalld_installed: true
package_gssproxy_removed: true
package_iprutils_removed: true
package_opensc_installed: true
package_policycoreutils_installed: true
package_rsyslog_installed: true
package_sendmail_removed: true
package_tmux_installed: true
package_tuned_removed: true
package_usbguard_installed: true
package_vsftpd_removed: true
```

```
- name: Ensure tftp-server is removed
  package:
    name: tftp-server
    state: absent
  tags:
  - CCE-82436-7
  - DISA-STIG-RHEL-08-040190
  - NIST-800-53-CM-6(a)
  - NIST-800-53-CM-7(a)
  - NIST-800-53-CM-7(b)
  - disable_strategy
  - high_severity
  - low_complexity
  - low_disruption
  - no_reboot_needed
  - package_tftp-server_removed
  when:
  - disable_strategy | bool
  - high_severity | bool
  - low_complexity | bool
  - low_disruption | bool
  - no_reboot_needed | bool
  ```

It would be adding a new variable `package_tftp-server_removed: true` and adding it to the conditional on the task above.
