### ISSUE TITLE
`Segmentation fault` with the version `0.1.58` on Debian 10 and Ubuntu 20.04 machines

### ISSUE THREAD

**Issue by mdedonno1337** [ComplianceAsCode/content#7718]
#### Description of problem:

When doing a `xccdf eval` on a Debian 10 and Ubuntu 20.04 machines, the scanner will `segfault` if using the version `0.1.58`, but will run normally when using the version `0.1.57`.
Note that the `report.html` file is written OK on disk, and usable without any problems.

The scanner is the same between runs, build from source, version 1.3.5.

The scanner has been also compiled on CentOS 8, and is working with versions `0.1.57` and `0.1.58`.

Since:
- the version `0.1.57` is working on Debian and Ubuntu
- the version `0.1.58` is not working on Debian and Ubuntu
- the two versions `0.1.57` and `0.1.58` are working on CentOS
- the scanner is compiled OK from source on all machines
- the same scanner has been used between each tests for each machine

, I suspect that some changes in the `ComplianceAsCode/content` between `0.1.57` and `0.1.58` has been done affecting only the Debian familly. 

I would like to have some guidance regarding on how to proceed and help finding the source of the issue.
I plan to investigate the issue by compiling myself the version `0.1.57` and `0.1.58`, re-test them, and `git bisect`/recompile until one commit is identified. 

PS: exactly the same behaviour is seen with the `Debian 11` file in the PR #7715. I thought that it could be an issue with my PR, but not sure anymore.

#### SCAP Security Guide Version:

```
OpenSCAP command line tool (oscap) 1.3.5
Copyright 2009--2021 Red Hat Inc., Durham, North Carolina.

==== Supported specifications ====
SCAP Version: 1.3
XCCDF Version: 1.2
OVAL Version: 5.11.1
CPE Version: 2.3
CVSS Version: 2.0
CVE Version: 2.0
Asset Identification Version: 1.1
Asset Reporting Format Version: 1.1
CVRF Version: 1.1
```

Working one:
```
mdedonno@openscap:~$ ./openscap/build/oscap_wrapper info scap-security-guide-0.1.57/ssg-debian10-ds.xml
Document type: Source Data Stream
Imported: 2021-07-29T14:53:51

Stream: scap_org.open-scap_datastream_from_xccdf_ssg-debian10-xccdf-1.2.xml
Generated: (null)
Version: 1.3
Checklists:
        Ref-Id: scap_org.open-scap_cref_ssg-debian10-xccdf-1.2.xml
                Status: draft
                Generated: 2021-07-29
                Resolved: true
                Profiles:
                        Title: Profile for ANSSI DAT-NT28 Average (Intermediate) Level
                                Id: xccdf_org.ssgproject.content_profile_anssi_np_nt28_average
                        Title: Profile for ANSSI DAT-NT28 High (Enforced) Level
                                Id: xccdf_org.ssgproject.content_profile_anssi_np_nt28_high
                        Title: Profile for ANSSI DAT-NT28 Minimal Level
                                Id: xccdf_org.ssgproject.content_profile_anssi_np_nt28_minimal
                        Title: Profile for ANSSI DAT-NT28 Restrictive Level
                                Id: xccdf_org.ssgproject.content_profile_anssi_np_nt28_restrictive
                        Title: Standard System Security Profile for Debian 10
                                Id: xccdf_org.ssgproject.content_profile_standard
                Referenced check files:
                        ssg-debian10-oval.xml
                                system: http://oval.mitre.org/XMLSchema/oval-definitions-5
                        ssg-debian10-ocil.xml
                                system: http://scap.nist.gov/schema/ocil/2
Checks:
        Ref-Id: scap_org.open-scap_cref_ssg-debian10-oval.xml
        Ref-Id: scap_org.open-scap_cref_ssg-debian10-ocil.xml
        Ref-Id: scap_org.open-scap_cref_ssg-debian10-cpe-oval.xml
Dictionaries:
        Ref-Id: scap_org.open-scap_cref_ssg-debian10-cpe-dictionary.xml
```

Not working one:

```
mdedonno@openscap:~$ ./openscap/build/oscap_wrapper info scap-security-guide-0.1.58/ssg-debian10-ds.xml
Document type: Source Data Stream
Imported: 2021-09-24T15:53:26

Stream: scap_org.open-scap_datastream_from_xccdf_ssg-debian10-xccdf-1.2.xml
Generated: (null)
Version: 1.3
Checklists:
        Ref-Id: scap_org.open-scap_cref_ssg-debian10-xccdf-1.2.xml
                Status: draft
                Generated: 2021-09-24
                Resolved: true
                Profiles:
                        Title: Profile for ANSSI DAT-NT28 Average (Intermediate) Level
                                Id: xccdf_org.ssgproject.content_profile_anssi_np_nt28_average
                        Title: Profile for ANSSI DAT-NT28 High (Enforced) Level
                                Id: xccdf_org.ssgproject.content_profile_anssi_np_nt28_high
                        Title: Profile for ANSSI DAT-NT28 Minimal Level
                                Id: xccdf_org.ssgproject.content_profile_anssi_np_nt28_minimal
                        Title: Profile for ANSSI DAT-NT28 Restrictive Level
                                Id: xccdf_org.ssgproject.content_profile_anssi_np_nt28_restrictive
                        Title: Standard System Security Profile for Debian 10
                                Id: xccdf_org.ssgproject.content_profile_standard
                Referenced check files:
                        ssg-debian10-oval.xml
                                system: http://oval.mitre.org/XMLSchema/oval-definitions-5
                        ssg-debian10-ocil.xml
                                system: http://scap.nist.gov/schema/ocil/2
Checks:
        Ref-Id: scap_org.open-scap_cref_ssg-debian10-oval.xml
        Ref-Id: scap_org.open-scap_cref_ssg-debian10-ocil.xml
        Ref-Id: scap_org.open-scap_cref_--__w--content--content--build--ssg-debian10-cpe-oval.xml
Dictionaries:
        Ref-Id: scap_org.open-scap_cref_--__w--content--content--build--ssg-debian10-cpe-dictionary.xml
```

#### Operating System Version:

```
mdedonno@openscap:~$ uname -a
Linux openscap 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux
mdedonno@openscap:~$ cat /etc/debian_version
10.11
```

#### Steps to Reproduce:

1. Install Debian 10 or Ubuntu 20.04, no particular options
2. Build the scanner from source; tests OK
3. wget https://github.com/ComplianceAsCode/content/releases/download/v0.1.58/scap-security-guide-0.1.58.zip 
4. ./openscap/build/oscap_wrapper xccdf eval --profile xccdf_org.ssgproject.content_profile_standard --report report.html scap-security-guide-0.1.58/ssg-debian10-ds.xml

#### Actual Results:

The not working scan:

```
mdedonno@openscap:~$ ./openscap/build/oscap_wrapper xccdf eval --profile xccdf_org.ssgproject.content_profile_standard --report report.html scap-security-guide-0.1.58/ssg-debian10-ds.xml

...

Title   Disable SSH Root Login
Rule    xccdf_org.ssgproject.content_rule_sshd_disable_root_login
Result  fail

./openscap/build/oscap_wrapper: line 31:  2822 Segmentation fault      "$b/run" "$b/utils/oscap" "$@"
mdedonno@openscap:~$
```

The working scan:
```
mdedonno@openscap:~$ ./openscap/build/oscap_wrapper xccdf eval --profile xccdf_org.ssgproject.content_profile_standard --report report.html scap-security-guide-0.1.57/ssg-debian10-ds.xml

...

Title   Disable SSH Root Login
Rule    xccdf_org.ssgproject.content_rule_sshd_disable_root_login
Result  fail

mdedonno@openscap:~$
```

#### Expected Results:

Not `segfault`
