### ISSUE TITLE
Verify `/boot/efi` mount options

### ISSUE THREAD

**Issue by jcpunk** [ComplianceAsCode/content#7848]
## Which products and profiles does the rule apply to?

Fedora, RHEL8, RHEL9

## Describe the configuration setting enforced by this rule.

The ESP partition should be mounted with options:

```
umask=0077,shortname=winnt
```

to ensure maximal compatibility with any other OS on the box, and restrict access to `root` only.

## Why is the configuration security relevant?

If the ESP partition is not set to `root` only access, the non-root user can change the way the system boots.

## How to check the configuration?

with the owner as `root`
```
template:
    name: mount_option
    vars:
        mountpoint: /boot/efi
        mountoption: umask=0077
        mount_has_to_exist: 'yes'
template:
    name: mount_option
    vars:
        mountpoint: /boot/efi
        mountoption: shortname=winnt
        mount_has_to_exist: 'yes'
```

### Is it order dependent? (does it need to be at certain place in the file?)

This is not order dependant

### What is correct and incorrect syntax?

Traditional mount syntax

## How to remediate

Add the missing optionsd

### Does any command need to be run?

No special commands beyond a remount with the new options.

## Are there going to be other rules like this one in the future? Is it worth creating template? (similar configuration format, similar remediation process...)

Yes, template already exists.

## Are there any caveats to be considered when testing?

This is only applicable for EFI systems.  It assumes the ESP partition is mounted under `/boot/efi`

## Is the configuration loaded directly by the <software> or is it stored in some intermediate database (similar to dconf)? (We want to edit the lowest level possible, if appropriate)

Text file `/etc/fstab`

## Is it possible to check / remediate this configuration in offline mode? (scanning containers or offline systems)

This option can be checked in offline mode.

##  Please provide security policy references if possible e.g. STIG
