### ISSUE TITLE
Bash/Ansible Remediation of `ensure_redhat_gpgkey_installed` doesn't consider CentOS Stream keys

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#8480]
#### Description of problem:
[Bash](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/bash/shared.sh) and [Ansible](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/ansible/shared.yml) remediation of rule [`ensure_redhat_gpgkey_installed`](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/rule.yml) do not remediate properly the CentOS Stream. It needs to be updated to remediate properly. The remediation needs to be aware of OS it's being executed on. Ansible already has a mechanism to check that: https://github.com/ComplianceAsCode/content/blob/68bc37a1905435aa39a00ca688e3a882945b1e0c/linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/ansible/shared.yml#L43

The bash remediation will need to check the /etc/os-release probably, similarly as it's done in: https://github.com/ComplianceAsCode/content/blob/68bc37a1905435aa39a00ca688e3a882945b1e0c/shared/checks/oval/installed_OS_is_centos9.xml#L27

Useful information:

Centos Stream 9 Key filepath: `/etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial`
Centos Stream 9 Key fingerprint: `99DB70FAE1D7CE227FB6488205B555B38483C65D`
It needs to be added to the product yaml: https://github.com/ComplianceAsCode/content/blob/master/products/rhel9/product.yml
A new yaml key needs to be added to the product yaml.

**Comment by arushai** [comment]
Same defect on **Rocky 9 and AlmaLinux 9**, not only CentOS Stream — and these are platforms the `rl9` playbooks are shipped for, so the remediation is dead in the playbook it ships in.

Measured against `scap-security-guide-0.1.81-1.el9_8.rocky.1.1` (`rl9-playbook-cis_server_l1.yml`), on a stock Rocky 9 host.

**The remediation is unreachable for two independent reasons**, not just the `ansible_distribution` gate already linked in the description:

```yaml
- name: 'Ensure Red Hat GPG Key Installed: Import RedHat GPG key'
  ansible.builtin.command: rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
  when:
  - gpg_key_directory_permission.stat.mode <= '0755'
  - (gpg_installed_fingerprints | difference(gpg_valid_fingerprints)) | length == 0
  - gpg_installed_fingerprints | length > 0      # <-- also always false here
  - ansible_distribution == "RedHat"             # <-- Rocky / AlmaLinux
```

`gpg_installed_fingerprints` is built from

```yaml
ansible.builtin.command: gpg --show-keys --with-fingerprint --with-colons "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"
changed_when: false
failed_when: false
```

and that file is not shipped by Rocky or Alma. With `failed_when: false` the task reports `ok` with empty stdout, `regex_findall` yields `[]`, and the length test fails. So even if the distribution gate were relaxed, the fingerprint condition would still block it — worth knowing for whoever picks this up, since fixing only the gate would not be enough.

**The four preparatory tasks are not gated at all** (`stat`, the `gpg` command, and the two `set_fact`s) and run on every host, reading a path that does not exist there.

**No visible failure**, which is probably why this has stayed quiet: the OVAL check returns `pass` on a stock Rocky 9 box in the same run's ARF, because DNF has the distribution's own key. So this is dead remediation content rather than a user-facing failure — but the gap is real, and a Rocky host that genuinely lost its signing key would not be remediated by this rule.

The `product.yml` approach proposed above for CentOS Stream would cover Rocky and AlmaLinux the same way. Happy to send a PR if that would help; I have not verified the other `rl9`/`al9` profile playbooks, only `cis_server_l1`.

*Found while building tooling that consumes SSG unmodified and classifies every playbook task into ordered phases — a task that can never run on any platform its playbook targets shows up as an anomaly in that pass.*
