### ISSUE TITLE
Ensure opensc is installed is failing conditional check despite being installed.

### ISSUE THREAD

**Issue by imcb** [ComplianceAsCode/content#9112]
While running the ansible-playbook for RHEL8-stig i have run into the following error: 

````
fatal: [localhost]: FAILED! => {
    "msg": "The conditional check 'package_opensc_installed | bool' failed. The error was: error while evaluating conditional (package_opensc_installed | bool): 'package_opensc_installed' is undefined\n\nThe error appears to be in '/home/ec2-user/disa-stig-rhel-8-ami/2-configinstance/ansible/roles/ansible-role-rhel8-stig/tasks/main.yml': line 5963, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Ensure opensc is installed\n  ^ here\n"
}
````
However I know I have installed the package already

````
Last metadata expiration check: 1:30:17 ago on Thu 07 Jul 2022 06:55:34 PM UTC.
Installed Packages
Name         : opensc
Version      : 0.20.0
Release      : 4.el8
Architecture : x86_64
Size         : 3.8 M
Source       : opensc-0.20.0-4.el8.src.rpm
Repository   : @System
From repo    : rhel-8-baseos-rhui-rpms
Summary      : Smart card library and applications
URL          : https://github.com/OpenSC/OpenSC/wiki
License      : LGPLv2+
Description  : OpenSC provides a set of libraries and utilities to work with smart cards. Its
             : main focus is on cards that support cryptographic operations, and facilitate
             : their use in security applications such as authentication, mail encryption and
             : digital signatures. OpenSC implements the PKCS#11 API so applications
             : supporting this API (such as Mozilla Firefox and Thunderbird) can use it. On
             : the card OpenSC implements the PKCS#15 standard and aims to be compatible with
             : every software/card that does so, too.
````

I should update with the play that is failing as well: 

````
- name: Ensure opensc is installed
  package:
    name: opensc
    state: latest
  when:
  - enable_strategy | bool
  - low_complexity | bool
  - low_disruption | bool
  - medium_severity | bool
  - no_reboot_needed | bool
  - package_opensc_installed | bool <
  - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
  tags:
  - CCE-80846-9
  - DISA-STIG-RHEL-08-010410
  - NIST-800-53-CM-6(a)
  - enable_strategy
  - low_complexity
  - low_disruption
  - medium_severity
  - no_reboot_needed
  - package_opensc_installed
````
